spring.application.name=class02
server.port=8080

# --- Actuator ---
# GET /actuator/health -> {"status":"UP", ...}  (usado por ALB Target Group / ECS / K8s)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
